### ISSUE TITLE
問い合わせ先メールアドレスの確認

### ISSUE THREAD

**Issue by yuichi-e** [pildre/stacknote-forum-ja#5]
readme.md記載のメールアドレスへ連絡したところ、当該プロジェクトと無関係の宛先のようでした。
ご確認をお願いします。

**Comment by dorokei** [comment]
@yuichi-e 
ご連絡いただきありがとうございます。
ご指摘の通りメールアドレスが間違っていました。ご迷惑をおかけし申し訳ありませんでした。
該当箇所は修正いたしましました。

また、正しいメールアドレスは下記になります。
info@stacknote.io
個別に不明点などありましたらこちらまでよろしくお願いいたします。

**Comment by yuichi-e** [comment]
@dorokei 
ご確認いただきありがとうございます。インストール時の問題についてご報告しようとしていました。
別途issueに追加させていただきますのでご確認いただければ幸いです。

**Comment by dorokei** [comment]
@yuichi-e 
どうもありがとうございます。大変助かります。
よろしくお願いいたします。
