### ISSUE TITLE
インストール時にセキュリティ警告が表示される

### ISSUE THREAD

**Issue by yuichi-e** [pildre/stacknote-forum-ja#6]
## バグレポート

インストール時にセキュリティ警告が表示される

### 環境情報

* OS: Windows 
* OS バージョン: 10 Pro 1903(build18362.175) 
* Stacknote アプリのバージョン: 0.1.0

### 再現方法

上記環境でStacknote-Setup-0.1.0.exeを実行

### 備考・スクリーンショット

![screenshot](https://user-images.githubusercontent.com/44597751/60065972-9ed57080-9740-11e9-8544-a7391cb11b31.png)

windowsセキュリティサンドボックス上で再度実行・インストールしたところ、特に問題は見受けられませんでした。細かなテストはできないためご確認いただければ幸いです。

**Comment by dorokei** [comment]
@yuichi-e 
ご連絡ありがとうございます！こちら確認させていただきます。
web版も利用可能ですので、セキュリティが気になるようでしたら[こちら](https://stacknote.io)を試していただけばと思います。
ご不便をおかけし申し訳ありませんm(_ _)m

**Comment by yuichi-e** [comment]
@dorokei 
ありがとうございます。ベータ版開発中とのことで大した問題ではないとは思うのですが、念のためご報告でした。
web版も試してみます！よろしくお願いします。
